name: lask_client
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  auto_route: ^6.3.0
  bot_toast: ^4.0.3
  dartz: ^0.10.1
  fluttertoast: ^8.2.1
  flutter_secure_storage: ^8.0.0
  lottie: ^2.3.2
  hooks_riverpod: ^2.3.5
  riverpod_annotation: ^2.1.0
  flutter_hooks: ^0.18.6
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.10
  carousel_slider: ^4.2.1
  flutter_typeahead: ^4.3.7
  image_picker: ^0.8.7+3
  intl_phone_number_input: ^0.7.3+1
  shimmer: ^2.0.0
  shared_preferences: ^2.1.0
  pinput: ^2.2.31
  get_it: ^7.3.0
  avatar_glow: ^2.0.2
  firebase_core: ^2.11.0
  cloud_firestore: ^4.6.0
  flutter_webrtc: ^0.9.29+hotfix.1
  audioplayers: ^4.0.1
  file_picker: ^5.3.0
#  flutter_localization: ^0.1.10
  intl: ^0.18.0
  web_socket_channel: ^2.4.0
  mime: ^1.0.4
  flutter_screenutil: ^5.8.4
  dio: ^5.1.1
  flutter_svg: ^1.1.6
  iconify_flutter: ^0.0.5
  flutter_launcher_icons: ^0.13.1
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  number_to_words_english: ^2.0.2
  flutter_local_notifications: ^14.0.0+2
  firebase_messaging: ^14.6.0
  app_settings: ^4.2.0
  pdf: ^3.10.1
  syncfusion_flutter_pdfviewer: ^21.2.3
  path_provider: ^2.0.15
  open_filex: ^4.3.2
  onesignal_flutter: ^3.5.0
  flutter_html: ^3.0.0-beta.1
  slide_countdown: ^0.6.0
  flutter_stripe: ^9.2.0
  flutter_dotenv: ^5.0.2
  keyboard_dismisser: ^3.0.0
  flutter_multi_select_items: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  auto_route_generator: ^6.2.0
  riverpod_lint: ^1.3.0
  riverpod_generator: ^2.2.0
  dropdown_search: ^5.0.6
  freezed: ^2.3.5
  json_serializable: ^6.6.2


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_circular.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Regular.ttf

#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
